### ISSUE TITLE
Template should be named according to Document details

### ISSUE THREAD

**Issue by giganscudo** [russelonato/ariel#14]
Given that the ticket number is Ticket123 and DBS version is DBSi5.0, the name of document should be similar to this:
1) PAFA: CATPDService_DBSi5.0 _PF_SR_Ticket123
2) TD: CATPDService_DBSi5.0_TD_Ticket123)

**Comment by russelonato** [comment]
@giganscudo Isn't there only a single template file being used? If say I run two executions with different details, wouldn't it make 2 template files with different names but same contents?

Or are you referring to the output file? The file that is cleaned by ariel?

**Comment by russelonato** [comment]
Addressed in issue #26 .
