### ISSUE TITLE
A colon is being displayed even when unnecessary

### ISSUE THREAD

**Issue by giganscudo** [russelonato/ariel#16]
It adds : even if it's not supposed to be included in the tag.

- [ ] Investigation
- [ ] Application of fix

**Comment by russelonato** [comment]
@giganscudo Can you provide an example of this? A few sample lines to serve as reference?

**Comment by russelonato** [comment]
![image](https://user-images.githubusercontent.com/33268077/49683391-5ab5b200-fb07-11e8-9eff-e146a855cb8e.png)
