### ISSUE TITLE
Append the list of failed downloads at the bottom of the logs

### ISSUE THREAD

**Issue by giganscudo** [russelonato/ariel#17]

**Comment by russelonato** [comment]
@giganscudo Few questions/

1) By "not downloaded", does this include files that are already existing on the target download folder prior to the execution of the download?

2) "Prompt the user to list" - Literally? In that case, wouldn't 15 minutes be insufficient?

3) Wouldn't it be better to just stop the execution entirely if a download is not successful, let the user know there may be a potential network issue instead? Is there a possibility that a user is unable to download now but 15 seconds later, it can be downloaded (one scenario I can think of is bottlenecks or files being used, but I am not familiar with the actual behaviour so please enlighten me).

**Comment by russelonato** [comment]
Addressed in pull issue #26, request #27 .
